import { motion } from 'framer-motion';
import { Laptop, Layers, Cpu, Code2, LayoutDashboard, Workflow, Check } from 'lucide-react';

const Services = () => {
  const servicesList = [
    {
      icon: <Laptop className="h-6 w-6 text-[#06B6D4]" />,
      title: "Full Stack Web Apps",
      description: "We build complete web applications combining clean frontend design with simple, secure databases to solve your business needs.",
      features: ["React & Node.js / FastAPI", "Mobile Responsive Layouts", "Secure User Auth & Database"]
    },
    {
      icon: <LayoutDashboard className="h-6 w-6 text-[#7C3AED]" />,
      title: "Dashboard & Admin Panels",
      description: "Need a way to view and manage your data? We build clean admin panels and dashboards to keep your operations organized.",
      features: ["Real-time Data Fetching", "Simple and clear charts", "CSV/Excel Export Option"]
    },
    {
      icon: <Cpu className="h-6 w-6 text-[#06B6D4]" />,
      title: "FastAPI Backend & APIs",
      description: "We build lightweight, reliable backend systems using Python's FastAPI. Clean endpoints that connect your frontend to databases or external services.",
      features: ["Fast and lightweight code", "Autogenerated API docs (OpenAPI)", "Secure data validation"]
    },
    {
      icon: <Code2 className="h-6 w-6 text-[#7C3AED]" />,
      title: "React.js Frontend Development",
      description: "Interactive user interfaces built with React.js. We focus on writing clean, modular components that make the site easy to maintain and scale.",
      features: ["Reusable component design", "Smooth Framer Motion transitions", "State management"]
    },
    {
      icon: <Layers className="h-6 w-6 text-[#06B6D4]" />,
      title: "Landing Pages & Business Websites",
      description: "Clean, professional websites designed to showcase your services, build trust, and convert visitors into clients.",
      features: ["SEO-friendly structure", "Fast load speed", "Contact form setup"]
    },
    {
      icon: <Workflow className="h-6 w-6 text-[#7C3AED]" />,
      title: "Website Maintenance & UI Improvements",
      description: "We help keep your website running smoothly, fix bugs, optimize performance, and improve outdated user interfaces.",
      features: ["Bug fixes & code cleanups", "UI visual refinements", "API integrations"]
    }
  ];

  return (
    <section id="services" className="relative py-24 bg-[#0B0B0B] border-t border-white/5">
      {/* Background Glows */}
      <div className="absolute top-0 right-1/4 w-96 h-96 rounded-full bg-[#06B6D4] opacity-[0.02] blur-[120px] pointer-events-none"></div>

      <div className="mx-auto max-w-7xl px-6 md:px-12 relative z-10">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-20">
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs font-bold uppercase tracking-widest text-[#06B6D4]"
          >
            Capabilities
          </motion.div>
          
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="mt-6 font-heading text-4xl sm:text-5xl font-extrabold text-white tracking-tight"
          >
            Simple, Effective Web Development Services
          </motion.h2>
          
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="mt-4 text-neutral-400 text-lg leading-relaxed font-light"
          >
            We focus on building websites that solve real business needs. Here are the core services we provide.
          </motion.p>
        </div>

        {/* Services Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {servicesList.map((service, idx) => (
            <motion.div
              key={service.title}
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: idx * 0.1 }}
              className="glow-card glass p-8 rounded-2xl flex flex-col justify-between group hover:translate-y-[-4px] hover:border-white/15 transition-all duration-300 relative overflow-hidden"
            >
              <div>
                {/* Floating Neon Background Light */}
                <div className="absolute top-0 right-0 w-24 h-24 bg-gradient-to-bl from-white/5 to-transparent rounded-bl-full pointer-events-none transition-all duration-300 group-hover:from-[#7C3AED]/10"></div>
                
                {/* Badge Icon */}
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-white/5 border border-white/10 mb-6 group-hover:bg-gradient-to-tr group-hover:from-[#7C3AED] group-hover:to-[#06B6D4] transition-all duration-300">
                  <span className="group-hover:text-white transition-colors duration-300">
                    {service.icon}
                  </span>
                </div>

                {/* Service Info */}
                <h3 className="font-heading text-2xl font-bold text-white mb-3 tracking-tight">
                  {service.title}
                </h3>
                
                <p className="text-neutral-400 text-sm leading-relaxed font-light mb-6">
                  {service.description}
                </p>
              </div>

              {/* Sub features checklist */}
              <ul className="space-y-2.5 pt-4 border-t border-white/5">
                {service.features.map((feat) => (
                  <li key={feat} className="flex items-center gap-2 text-xs font-medium text-neutral-300">
                    <span className="flex h-4.5 w-4.5 items-center justify-center rounded-full bg-neutral-900 text-[#06B6D4]">
                      <Check className="h-3 w-3" />
                    </span>
                    {feat}
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>

      </div>
    </section>
  );
};

export default Services;
